### ISSUE TITLE
HttpNumThreadsの既定値について

### ISSUE THREAD

**Issue by xtne6f** [abt8WG/EDCB#10]
EpgTimer/Setting/SetBasicView.xaml.csのHttpNumThreadsですが、コミット d806a120ad5670134fa3f8d65e595cbed34d377d 以降の既定値は3→5に変更したので、もし見逃している場合は更新したほうがよいかもしれません。
// スレッド数5はモダンな多くのブラウザで読み込みがもたつかない(経験的な)最小値です

**Comment by abt8WG** [comment]
修正したつもりになっていて修正し忘れていました。
有難うございます。
